version: '3.8'

services:
  main:
    build: .
    ports:
      - "5100:2831"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
